config/routes.rb
FenixReader::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :channels 
  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :feed_entries do
    resources :comments
  end

  scope module: 'feed_entries', as: :feeds do
    post :subscribe
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :feed_entries
  belongs_to :user
  before_save :check_url
  before_save :check_user_space
  before_save :set_title
  after_create :update_feeds
  attr_accessible :url

  # IF feedzirra finds a parser for the xml that the url returned then the 
  # URL is fine.
  def check_url
    xml = get_response(url)
    parser = Feedzirra::Feed.determine_feed_parser_for_xml(xml)
    !parser.nil?
  end
    
  def set_title
    xml = get_response(url)
    feed = Feedzirra::Feed.parse(xml)
    self.title ||= feed.title
  end
  
  def check_user_space
    user.channels.count < user.max_channels
  end
    
  def update_feeds
    feed = get_parsed_feed
    add_entries(feed.entries) if feed.respond_to? :entries
  end

  def get_response(url)
    @xml ||= Net::HTTP.get_response(URI.parse(url)).body
  end
  

  def get_parsed_feed
    Feedzirra::Feed.fetch_and_parse(url)
  end

  def self.update_feeds
    all.each {|c| c.update_feeds }
  end

  def add_entries(entries)
    entries.each do |entry|
      unless feed_entries.exists? guid: entry.id
        feed_entries.create!( title: entry.title, summary: entry.summary, url: entry.url,
          published_at: entry.published, guid: entry.id)
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :feed_entry
  attr_accessible :text
end

app/models/feed_entry.rb
class FeedEntry < ActiveRecord::Base
  belongs_to :channel
  has_many :comments
  scope :starred, where( 'stars <> 0' )
  scope :summary, proc { |summary| where(['summary LIKE ?', "%#{summary}%"]) }
  scope :title, proc { |title| where(['title LIKE ?', "%#{title}%"]) }
  default_scope order('published_at DESC')

  attr_accessible :guid, :published_at, :summary, :title, :url, :channel_id, :stars
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :channels
  has_many :feed_entries, through: :channels
   
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation,
                  :remember_me, :provider, :uid, :avatar_size
  
  def add_channel(url)
    self.channels.create(url: url) 
  end

  # find_for_twitter and find_for_google
  
  def self.find_for_google_oauth2(access_token)
    find_for_service(:google_oauth2, access_token[:uid])
  end

  def self.find_for_twitter(access_token)
    find_for_service(:twitter, access_token[:uid])
  end
  
  private
  
  def self.find_for_service(provider, uid)
    user = User.find_or_initialize_by_uid_and_provider(uid: uid ,
      provider: provider, password: Devise.friendly_token[0,20],
      email: "#{provider}_user_#{uid}@fenix-reader.com")
    user.skip_confirmation! 
    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def after_sign_in_path_for(resource)
    feed_entries_path
  end

  unless config.consider_all_requests_local
    rescue_from ActionController::RoutingError , with: :render_404
  end

  private

  def render_404
    flash[:error] = 'The url you tried to access seems incorrect'
    redirect_to root_path
  end
end

app/controllers/channels_controller.rb
class ChannelsController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :index, :edit, :destroy, :update

  protected
  def begin_of_association_chain
    current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :create
  belongs_to :feed_entry

  def create
    create! do |format|
      format.js { render nothing: true }
    end
  end
end

app/controllers/feed_entries_controller.rb
class FeedEntriesController <  InheritedResources::Base
  before_filter :authenticate_user!
  actions :index, :edit, :update
  has_scope :starred, :type => :boolean
  has_scope :summary
  has_scope :title

  def update
    update! do |format|
      format.js { render nothing: true }
    end
  end

  def subscribe
    unless current_user.add_channel(params[:url])
      flash[:error] = 'Can not subscribe to this url. Verify that is a valid rss/atom service'
    end
    render :index
  end

  protected
  def begin_of_association_chain
    current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  [:twitter, :google_oauth2].each do |service|
    define_method(service) do
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.send("find_for_#{service}", request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
        
        set_flash_message(:notice, :success,kind: service.to_s.capitalize) if is_navigational_format?
      else
        session["devise.#{service.to_s}_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{user.avatar_size}"
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  # Since we are showing devise login and signup forms in the home page
  # we need to specify the following resource_name, resource and devise_mapping
  def resource_name
    :user 
  end

  def resource
    @resource ||= User.new
  end 

  def resource
    @resource ||= User.new
  end 
  
  def resource_class
    devise_mapping.to
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end 
end

app/views/channels/_form.html.haml
= form_for @channel do |f|
  - if @channel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@channel.errors.count, "error")} prohibited this channel from being saved:"
      %ul
        - @channel.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_field :url
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/channels/edit.html.haml
.well
  %h1 Editing channel

  = render 'form'

app/views/channels/index.html.haml
.well
  %h1 Listing channels

  %table.table.table-bordered
    %tr
      %th url
      %th title 
      %th
      %th

    - @channels.each do |channel|
      %tr
        %td= channel.url
        %td= channel.title
        %td= link_to 'Edit', edit_channel_path(channel)
        %td= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' }

app/views/channels/show.html.haml
%p#notice= notice

%p
  %b String:
  = @channel.string
%p
  %b References:
  = @channel.references

= link_to 'Edit', edit_channel_path(@channel)
\|
= link_to 'Back', channels_path

app/views/comments/_list.html.haml
%ul.comments
  - comments.each do |comment|
    %li
      %p= comment.text

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/feed_entries/index.html.haml
.span4
  .well
    = form_tag(feeds_subscribe_path) do 
      = text_field_tag 'url','', placeholder: 'url'
      = button_tag 'Subscribe',class: 'btn', :disable_with => "Please wait..."
  .well
    %form#filters
      =text_field_tag :summary, '', placeholder: 'Search by summary'
      =text_field_tag :title, '', placeholder: 'Search by title'
      = button_tag 'Search',id: 'search',class: 'btn', :disable_with => "Please wait..."

.span7.feed_entries
  - if @feed_entries
    - @feed_entries.each do |feed|
      %li.well.feed_entry{id: "feed_entry_#{feed.id}"}
        =link_to feed.title, feed.url
        %br
        = feed.published_at 
        = raw feed.summary
        %hr
        = form_for feed, remote: true do |f|
          = f.select :stars, ['no Stars', nil] + (1..5).collect {|i| [  "#{i} star", i ] }, {},
            class: 'feed_entry_stars'
        %hr
        = form_for [ feed, Comment.new ],remote: true do |f|
          = render 'comments/list', comments: feed.comments
          = f.text_area :text, cols: 90, rows: 4, placeholder: 'Comment in here',
            class: 'comment_input'
        

app/views/feeds/index.html.haml
.span4.well

  = form_tag(feeds_subscribe_path) do
    = text_field_tag 'url','', placeholder: 'url'
    = button_tag 'Subscribe',class: 'btn', :disable_with => "Please wait..."

.span7
  - @feeds.each do |f|
    .well
      .control-group
        %label.control-label
          Title
          .controls
            =link_to f.title, f.url
      .control-group
        %label.control-label
          Published date
          .controls
            = f.published_at 
      .control-group
        %label.control-label
          summary
          .controls
            =raw f.summary
  

    

app/views/home/index.html.haml
.span5
  .well
    =render 'devise/sessions/new'
.span5.offset1
  .well
    =render 'devise/registrations/new'

app/views/layouts/_messages.html.haml
- {'error' => 'error', 'warning' => 'warning',
   'notice' => 'success', 'message' => 'info'}.each do |header, classname|
  %p{ :class => "alert alert-#{classname} x-flash-#{header} display-none" }
    %span.text
    %a.close( data-dismiss="alert" ) ×
- if notice
  %p#main_alert_notice.alert.alert-info
    %a.close( data-dismiss="alert" ) ×
    = raw notice
- if alert
  %p#main_alert_error.alert.alert-error
    %a.close( data-dismiss="alert" ) ×
    = raw alert
   

- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Fenix Reader", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'All Feeds', feed_entries_path
    %li
      = link_to 'Starred', feed_entries_path(starred: true)
    %li
      = link_to 'Subscribed channels', channels_path
    %li
      = link_to 'Edit account', edit_user_registration_path
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Fenix Reader"
      %meta{:content => content_for?(:description) ? yield(:description) : "Fenix Reader", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            = render 'layouts/messages'
            = yield
          %footer
      / ! end of .container
    / ! end of #main